### ISSUE TITLE
Using Zabbix.NET from powershell.

### ISSUE THREAD

**Issue by finalbeta** [Vidlec/Zabbix.NET#3]
Hi, thank you again for this library. 
I'm glad I've been able to contribute a little to your project. 

I personally needed to access Zabbix from inside a powershell script also. I've probably made that hard on myself by using your library. But I liked the fact that it's flexible. 
So after doing what I needed inside C# I tried using the library from Powershell. I've translated your example for c# to powershell  (with the help from #powershell on freenode irc) and added it to the readme. 
Perhaps you can pull my latest commit to your branch too. 

Best regards
Jochen

**Comment by Vidlec** [comment]
Thank you for your contribution! :) 
Merged your code
