### ISSUE TITLE
solution file issue

### ISSUE THREAD

**Issue by trigifu** [Vidlec/Zabbix.NET#6]
The included solution file: ZabbixApi.sln has 2 projects that are not part of the github repository.
"..\ZabbixApiTest\ZabbixApiTest\ZabbixApiTest.csproj"
"..\..\..\Documents\Visual Studio 2015\Projects\ZabbixApiTestPowershell\ZabbixApiTestPowershell.pssproj"

**Comment by Vidlec** [comment]
Removed from solution.
